package com.yourproject.resource.currency;

import com.yourproject.resource.model.mongo.Currency;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.util.Optional;

/**
 * {@link Currency} repository extending mongo repository with autogenerated method implementations.
 */
public interface CurrencyRepository extends MongoRepository<Currency, String> {

    /**
     * Find currency by code.
     *
     * @param code currency code.
     * @return optional with currency.
     */
    Optional<Currency> findByCode(String code);
}
